server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  config:
    import: "configserver:http://config-service:8762"
  main:
    allow-bean-definition-overriding: true




