server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    name: order-service
  cloud:
    config:
      uri: http://localhost:8762