server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    name: inventory-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8762"


#  datasource:
#    url: jdbc:mysql://localhost:3306/inventory  # URL to your MySQL database
#    username: root                          # Your MySQL username
#    password: password                      # Your MySQL password
#    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver
#    jpa:
#      hibernate:
#        ddl-auto: update                      # Can be set to none, validate, update, or create
#      show-sql: true                          # Enables logging of SQL statements
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5Dialect  # Dialect for MySQL 5.x



